name       : intel-tbb
version    : 4.4
release    : 2
source     :
    - https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb44_20150728oss_src.tgz : e9534f3238e6f7b34f9d0a78cb8604da1c5a611c5a2569fdd9cc90e06339538a
license    : GPL-2.0
component  : programming
summary    : High level abstract threading library
description: |
    High level abstract threading library
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then # 32-bit stuff
        %make arch=ia32
    else
        %make
    fi
install    : |
    mkdir -p $installdir/usr/include
    mkdir -p $installdir/%libdir%
    install -m755 build/linux_*/*.so* $installdir/%libdir%/
    cp -a include/tbb $installdir/usr/include/
