name       : intel-tbb
version    : '2019.3'
release    : 5
source     :
    - https://github.com/01org/tbb/archive/2019_U3.tar.gz : b2244147bc8159cdd8f06a38afeb42f3237d3fc822555499d7ccfbd4b86f8ece
license    : Apache-2.0
component  : programming
emul32     : yes
summary    : High level abstract threading library
description: |
    Intel(R) Threading Building Blocks (TBB) lets you easily write parallel C++ programs that take full advantage of multicore performance, that are portable, composable and have future-proof scalability.
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then # 32-bit stuff
        %make arch=ia32
    else
        %make
    fi
install    : |
    mkdir -p $installdir/usr/include
    mkdir -p $installdir/%libdir%
    install -m00755 build/linux_*/*.so* $installdir/%libdir%/
    cp -a include/tbb $installdir/usr/include/
