name       : intel-tbb
version    : '2019.5'
release    : 7
source     :
    - https://github.com/oneapi-src/oneTBB/archive/refs/tags/2019_U5.tar.gz : abf9236e6ec9a3675fa59ab56c2192c7ab4f7096a82af118e8efa514b2541578
license    : Apache-2.0
component  : programming
emul32     : yes
summary    : High level abstract threading library
description: |
    Intel(R) Threading Building Blocks (TBB) lets you easily write parallel C++ programs that take full advantage of multicore performance, that are portable, composable and have future-proof scalability.
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then # 32-bit stuff
        %make arch=ia32
    else
        %make
    fi
install    : |
    mkdir -p $installdir/usr/include
    mkdir -p $installdir/%libdir%
    install -m00755 build/linux_*/*.so* $installdir/%libdir%/
    cp -a include/tbb $installdir/usr/include/
