name       : intel-tbb
version    : '2021.5'
release    : 11
source     :
    - https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.5.0.tar.gz : e5b57537c741400cf6134b428fc1689a649d7d38d9bb9c1b6d64f092ea28178a
license    : Apache-2.0
component  : programming
emul32     : yes
summary    : High level abstract threading library
description: |
    Intel(R) Threading Building Blocks (TBB) lets you easily write parallel C++ programs that take full advantage of multicore performance, that are portable, composable and have future-proof scalability.
optimize   : lto
builddeps  :
    - libgomp-32bit
environment: |
    export GCC_IGNORE_WERROR=1
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
